Feat: amendments and revisions page [WIP]
bcgov/cas-cif pull request #1070
Opened 2022-09-07 01:17 UTC by mikevespi

- Added Amendments and Other Revisions to the task list
- Added `ProjectRevisionChangeLog` page with a table of `ProjectRevisionTableRow`

Still to do: 
- update the `tableFilters` in `ProjectRevisionChangeLog`
- populate the "effective date" and "updated" fields with their appropriate values (just have placeholders in there atm)
- test

2022-09-21 18:04 UTC, pbastia requested changes
A minor refactor, we might want to do this in a separate PR to speed things up

2022-09-26 18:58 UTC, BCerki commented
There's a bug where the table sizing bounces around after filtering: https://www.loom.com/share/9a293b7088cb42219005003e43a262ce

2022-09-27 17:28 UTC, bc-cas submitted a review, later dismissed
looks great!! just needs a rebase

2022-09-27 17:39 UTC, Sepehr-Sobhani commented
> There's a bug where the table sizing bounces around after filtering: https://www.loom.com/share/9a293b7088cb42219005003e43a262ce

Thanks for noticing this. going to make a tech debt card for that and merge this PR to unblock other issues.

2022-09-27 17:43 UTC, Sepehr-Sobhani commented on app/cypress/integration/cif/project-revision-change-logs.spec.js
> +    cy.get("thead th").contains("Effective Date").click();
It's not a duplicate, we need to click this field twice to get the DESC order but you're right, this is confusing so I'm gonna add a comment here for future reference.

2022-09-27 18:25 UTC, pbastia approved these changes

2022-09-27 18:49 UTC, merged