Fix/report auto generation timezone
bcgov/cas-cif pull request #1140
Opened 2022-10-17 23:02 UTC by Sepehr-Sobhani

[ZH Card](https://app.zenhub.com/workspaces/climate-action-secretariat-60ca4121764d710011481ca2/issues/bcgov/cas-cif/1136)

2022-10-18 16:02 UTC, pbastia submitted a review, later dismissed
very nice

2022-10-18 16:16 UTC, Sepehr-Sobhani commented
> very nice

@pbastia Unfortunately this fix was not enough. still looking for a solution.

2022-11-02 21:41 UTC, pbastia requested changes
Awesome! Just a style comment

2022-11-02 21:41 UTC, pbastia commented on schema/deploy/mutations/generate_reports@1.0.0-rc.5.sql
> +  returns setof cif.form_change as $generate_reports$
Just a line break for consistency with how we've written those in the past

```suggestion
returns setof cif.form_change as 
$generate_reports$
```

2022-11-02 22:04 UTC, pbastia approved these changes

2022-11-02 22:11 UTC, merged