chore: discard funding parameter discards additional funding sources
bcgov/cas-cif pull request #1354
Opened 2023-01-18 01:05 UTC by mikevespi

card: https://app.zenhub.com/workspaces/climate-action-secretariat-60ca4121764d710011481ca2/issues/gh/bcgov/cas-cif/1226

2023-01-24 21:21 UTC, BCerki approved these changes

2023-01-25 18:47 UTC, pbastia requested changes
Nitpicking for readable variable names 😛 

Very nice

2023-01-25 18:47 UTC, pbastia commented on schema/deploy/mutations/discard_funding_parameter_form_change.sql
> +afs_form_change_record record;
```suggestion
additional_funding_source_form_change_record record;
```

2023-01-26 22:33 UTC, pbastia approved these changes

2023-01-26 22:50 UTC, merged