1453 create application
bcgov/cas-cif pull request #1558
Opened 2023-03-17 17:18 UTC by BCerki

Card: https://github.com/bcgov/cas-cif/issues/1453

2023-03-22 22:10 UTC, tmastrom reviewed
Good slice! I'm wondering if we could get the jsonSchemaForm from the database?

2023-03-22 22:20 UTC, BCerki commented
> Good slice! I'm wondering if we could get the jsonSchemaForm from the database?

I thought about it, but the fields will probably change a lot throughout the slices, and if the schema's in the db, every time we want to update it we'll need to do a sqitch migration. And doing 10 sqitch migrations will probably be more time-consuming than refactoring it later

2023-03-22 23:22 UTC, dleard requested changes

2023-03-22 23:22 UTC, dleard commented on app/components/Form/ProjectRfpForm.tsx
> +  query: any;
Let's replace this `any` type. Maybe something like this?
```suggestion
  query: ProjectRfpForm_query$key;
```

2023-03-22 23:22 UTC, dleard commented on app/lib/theme/widgets/SelectParentWidget.tsx
> +  list: [{ rowId: any; year?: number }];
Remove `any` type
```suggestion
  list: [{ rowId: number; year?: number }];
```

2023-03-22 23:22 UTC, dleard commented on app/lib/theme/widgets/SelectParentWidget.tsx
> +  displayIfChildrenEmpty: any;
Remove `any` type
```suggestion
  displayIfChildrenEmpty: string;
```

2023-03-22 23:22 UTC, dleard commented on app/pages/cif/project-revision/[projectRevision]/form/[formIndex]/index.tsx
> +import { useFormIndexHelpers } from "../../../../../../hooks/useFormIndexHelpers";
We shouldn't need all the ../../.. here
```suggestion
import { useFormIndexHelpers } from "hooks/useFormIndexHelpers";
```

2023-03-23 16:46 UTC, tmastrom commented
> 

That's a really good plan while things are in flux

2023-03-24 22:13 UTC, tmastrom commented on app/cypress/support/commands.js
> +      .select(fundingStream);
I'm not able to notice a difference in testing with just one or two of these statements. Interestingly, asserting that the funding stream should be visible after it is selected causes an error `cy.contains(fundingStream).should("be.visible"); // error`

2023-03-30 17:29 UTC, dleard requested changes
A couple things I found during manual testing:

Clicking submit application overview after filling out the Project Overview & Legal Name directs me to 404 page not found.

If "Return to Dashboard" is clicked while the project is in draft, there is no way to get back to that draft

2023-03-30 17:29 UTC, dleard commented on app/pages/cif-external/project-revision/[projectRevision]/form/[formIndex]/index.tsx
> +  console.log(
Remove console log

2023-03-30 17:29 UTC, dleard commented on app/pages/cif-external/project-revision/[projectRevision]/form/[formIndex]/index.tsx
> +  console.log("mode", mode);
Remove console log

2023-03-30 17:29 UTC, dleard commented on app/routes/pageRoutes.ts
> +  console.log("is internal", isInternal);
Remove console log

2023-03-30 20:42 UTC, BCerki commented
> A couple things I found during manual testing:
> 
> Clicking submit application overview after filling out the Project Overview & Legal Name directs me to 404 page not found.
> 
> If "Return to Dashboard" is clicked while the project is in draft, there is no way to get back to that draft

The next pages (attachments, summary) aren't part of this ticket, so that's why you get a 404 page. Getting back to the draft/edit also isn't part of this ticket (or the slice).

2023-03-31 17:46 UTC, merged