Feat: 1231 Show calculated diffs on overview form
bcgov/cas-cif pull request #1638
Opened 2023-05-01 22:48 UTC by BCerki

Card: https://app.zenhub.com/workspaces/climate-action-secretariat-60ca4121764d710011481ca2/issues/gh/bcgov/cas-cif/1231

2023-05-03 21:50 UTC, tmastrom requested changes
Rank functionality is working well with the new computed column!

### Frontend Comments: 
Is this what the diff comment should say for the Rank?
![Screenshot 2023-05-03 at 2 36 01 PM](https://user-images.githubusercontent.com/36525329/236057055-847ba74a-9eb5-441c-9133-30aa775dd66f.jpg)

Nit: it could be nice to limit the size of the rank message before a value is entered to keep the width of the form consistent 

### Backend Comments: 
`sqitch verify` is failing with the following message 
```
  - tables/report_type_003 ............................................................................ 2023-05-03 14:44:12.077 PDT [28614] ERROR:  update or delete on table "report_type" violates foreign key constraint "reporting_requirement_report_type_fkey" on table "reporting_requirement" 
 ```

2023-05-03 21:50 UTC, tmastrom commented on schema/deploy/computed_columns/form_change_rank.sql
> +      )
good catch

2023-05-04 19:07 UTC, BCerki commented
> Rank functionality is working well with the new computed column!
> 
> ### Frontend Comments:
> Is this what the diff comment should say for the Rank? ![Screenshot 2023-05-03 at 2 36 01 PM](https://user-images.githubusercontent.com/36525329/236057055-847ba74a-9eb5-441c-9133-30aa775dd66f.jpg)
> 
> Nit: it could be nice to limit the size of the rank message before a value is entered to keep the width of the form consistent
> 
> ### Backend Comments:
> `sqitch verify` is failing with the following message
> 
> ```
>   - tables/report_type_003 ............................................................................ 2023-05-03 14:44:12.077 PDT [28614] ERROR:  update or delete on table "report_type" violates foreign key constraint "reporting_requirement_report_type_fkey" on table "reporting_requirement" 
> ```

Thanks for catching the "none" latest committed diff! I'll update the rest of the calculated diff cards to include that.

Nit: The message came from the designers back when this widget was first implemented so I'll make a card/ask them

Sqitch verify: I couldn't reproduce this, though when I ran `sqitch verify` I got 17 other errors, so I'll bring that up with in Developers. I'm not sure it's related to this PR

2023-05-04 23:30 UTC, tmastrom approved these changes

2023-05-04 23:33 UTC, merged