Feat: 1462 attachment form
bcgov/cas-cif pull request #1682
Opened 2023-05-23 21:19 UTC by BCerki

card: https://app.zenhub.com/workspaces/climate-action-secretariat-60ca4121764d710011481ca2/issues/gh/bcgov/cas-cif/1462

2023-05-31 23:01 UTC, Sepehr-Sobhani requested changes
Looks great 🤩 some minor changes are required.

2023-06-02 15:34 UTC, BCerki commented on app/components/Form/ProjectAttachmentsForm.tsx
> -        pageQuery={AttachmentsQuery}
I don't have a page query anymore now that attachments are a component, so I can't use this prop. Not sure if I need to do something to replace it? This is what it was doing:

```/**
   * The top-level query used by the page rendenring the table.
   * If provided, when the table filters, ordering or pagination are updated,
   * the table will reload the query before updating the router,
   * preventing a render with the Suspense fallback while the new data is being fetched.
   */
  pageQuery?: GraphQLTaggedNode;

2023-06-02 15:39 UTC, BCerki commented on app/lib/relay/client.ts
There's a batch error if the middleware is in the old order. We hit it on CIIP too

2023-06-02 20:43 UTC, Sepehr-Sobhani commented on schema/test/unit/mutations/discard_project_attachment_form_change_test.sql
> +    from cif.discard_project_attachment_form_change(2)
I tried removing this part and test passed, Am I doing something wrong?
```
    with record as (
    select row(form_change.*)::cif.form_change
    from cif.form_change where id=2
    )
```

2023-06-02 23:08 UTC, BCerki commented on schema/test/unit/mutations/discard_project_attachment_form_change_test.sql
> +    from cif.discard_project_attachment_form_change(2)
Probably I had something wrong originally. Thanks, I'll simplify it!

2023-06-02 23:26 UTC, Sepehr-Sobhani commented
@BCerki Just another question, Do we also need to have `latestCommittedFormChangesFor` in the project attachment form summary too?

2023-06-05 15:50 UTC, BCerki commented
> @BCerki Just another question, Do we also need to have `latestCommittedFormChangesFor` in the project attachment form summary too?

That's part of https://github.com/bcgov/cas-cif/issues/1680

2023-06-06 16:44 UTC, merged