Fix: 1526 hide nav bar when user IDIR is unauthorized
bcgov/cas-cif pull request #1704
Opened 2023-05-31 16:10 UTC by BCerki

card: https://app.zenhub.com/workspaces/climate-action-secretariat-60ca4121764d710011481ca2/issues/gh/bcgov/cas-cif/1526

2023-06-06 18:22 UTC, Sepehr-Sobhani requested changes
Looks great 🤩  just some minor comments.

2023-06-07 21:34 UTC, BCerki commented on app/tests/unit/components/Layout/DefaultLayout.test.tsx
> +  });
There's no `unauthorized_idir` component, so I don't think we need an `unauthorized_idir` file. I did move this into a `Navigation` component test though

2023-06-07 21:42 UTC, Sepehr-Sobhani commented on app/tests/unit/components/Layout/DefaultLayout.test.tsx
> +  });
We have `unauthorized_idir.tsx` and `unauthorized_idir.test.tsx` files. wouldn't it be better to move tests there? just a suggestion though.

2023-06-07 21:45 UTC, BCerki commented on app/tests/unit/components/Layout/DefaultLayout.test.tsx
> +  });
Missed that somehow, I'm going to do this PR slightly differently then

2023-06-07 22:05 UTC, Sepehr-Sobhani approved these changes
🥳

2023-06-08 15:28 UTC, merged