1644 login redirect functionality
bcgov/cas-cif pull request #1725
Opened 2023-06-14 21:41 UTC by JoshLarouche

[zenhub 1644](https://app.zenhub.com/workspaces/climate-action-secretariat-60ca4121764d710011481ca2/issues/gh/bcgov/cas-cif/1644)

2023-06-23 23:37 UTC, Sepehr-Sobhani requested changes
Great Job 👍 Just a couple of changes are required.

2023-06-23 23:37 UTC, Sepehr-Sobhani commented on app/components/Layout/Navigation.tsx
I think we can do a bit of refactoring on lines 37 through 54, something like:
```
  let rightSide = isLoggedIn ? (
    <>
      {userProfileComponent}
      <LogoutForm />
    </>
  ) : (
    router.pathname !== "/" && (
      <div
        style={{
          display: "flex",
          flexDirection: "row",
          gap: "1.25em",
        }}
      >
        <LoginForm />
        {showExternalOperatorsLogin && <LoginForm isExternal={true} />}
      </div>
    )
  );
```

2023-06-23 23:37 UTC, Sepehr-Sobhani commented on app/components/Session/LoginForm.tsx
we can also simplify things here a little bit and have less code to maintain:
```
      <form id="login-buttons" action={loginURI} method="post">
        <Button
          type="submit"
          variant={
            router.pathname.includes("login-redirect")
              ? "secondary-inverse"
              : isExternal && "secondary"
          }
        >
          {isExternal ? "External User Login" : "Administrator Login"}
        </Button>
      </form>
```

2023-06-23 23:37 UTC, Sepehr-Sobhani commented on app/components/Session/LoginForm.tsx
Also, we need to tweak `loginURI` too, currently, this part of the AC is not in place:
`Then I am redirected back to the page I was trying to get to.`
I've played with the code and something like this could be a solution:
```
  let loginURI = "/login";

  if (router.query.redirectTo)
    loginURI += `?redirectTo=${encodeURIComponent(
      router.query.redirectTo as string
    )}`;
  else if (isExternal)
    loginURI += `?redirectTo=${encodeURIComponent(
      getExternalUserLandingPageRoute().pathname as string
    )}`;
```

2023-06-23 23:37 UTC, Sepehr-Sobhani commented on app/tests/unit/pages/login-redirect.test.tsx
I believe it would be advantageous to conduct a test here on the redirect functionality for external users.

2023-06-26 18:39 UTC, JoshLarouche commented on app/components/Layout/Navigation.tsx
Good idea! Changed!

2023-06-26 18:40 UTC, JoshLarouche commented on app/components/Session/LoginForm.tsx
Good call! Changed!

2023-06-26 18:40 UTC, JoshLarouche commented on app/components/Session/LoginForm.tsx
Good catch I tested mostly with the admin login! Changed!

2023-06-26 18:42 UTC, JoshLarouche commented on app/tests/unit/pages/login-redirect.test.tsx
After discussion with @Sepehr-Sobhani  it was determined that it does not make sense to test this for now until we add more external user functionality.

2023-06-28 00:06 UTC, Sepehr-Sobhani approved these changes

2023-06-28 15:23 UTC, merged