Refactor: 1361 emissions intensity schema
bcgov/cas-cif pull request #1771
Opened 2023-07-06 15:12 UTC by BCerki

card: https://app.zenhub.com/workspaces/climate-action-secretariat-60ca4121764d710011481ca2/issues/gh/bcgov/cas-cif/1361

A couple notes:
- There's a previously existing bug in the calculated value widget: https://app.zenhub.com/workspaces/climate-action-secretariat-60ca4121764d710011481ca2/issues/gh/bcgov/cas-cif/736. I was able to improve the display a little as part of required work for this ticket (removed 0/0/Not added), but bug remains
- Turned up another bug: https://app.zenhub.com/workspaces/climate-action-secretariat-60ca4121764d710011481ca2/issues/gh/bcgov/cas-cif/1740

2023-07-06 22:23 UTC, dleard requested changes
I found a few things that caused the migration to break when deploying over a proper dataset.

2023-07-07 21:27 UTC, dleard requested changes

2023-07-07 21:27 UTC, dleard commented on schema/deploy/mutations/create_project_revision.sql
There is an issue in this file [here](https://github.com/bcgov/cas-cif/blob/db7b89ef4a3eded800f4d9f61a9980541a51f114/schema/deploy/mutations/create_project_revision.sql#L67) where the reportType of 'TEIMP' needs be be ignored like we're ignoring 'Project Summary Report'.
This is causing the json_schema_name to be set to 'reporting_requirement' when it should be 'emission_intensity', which in turn causes the data not to propagate to the emission intensity report table on commit and the diff to be missing data.

2023-07-10 17:22 UTC, BCerki commented on schema/data/prod/json_schema/emission_intensity.json
> +        "title": "Report Due Date"
add `defaultValue: null` for all optional fields
type should `type: string[] || null` for optional fields

2023-07-10 17:23 UTC, BCerki commented on schema/data/prod/json_schema/emission_intensity.json
> +        "title": "Report Due Date"
to test--clear an optional field, commit, and go check db to make sure it's null in the db (if the previously committed value is still there, it didn't work)

2023-07-10 17:25 UTC, BCerki commented on schema/data/prod/json_schema/emission_intensity.json
> +        "title": "Report Due Date"
for date widgets, might not need to add defaultValue because the widget handles it, check this

2023-07-10 17:41 UTC, BCerki commented on app/data/jsonSchemaForm/emissionIntensityUiSchema.ts
> +  },
I deleted these two and they're gone from the db: 
![image](https://github.com/bcgov/cas-cif/assets/77306764/dfd9cd92-d217-4e45-b999-2b2fcbfdf3a1)

2023-07-10 17:41 UTC, BCerki commented on app/data/jsonSchemaForm/emissionIntensityUiSchema.ts
> +  postProjectEmissionIntensity: {
deleted this and it's gone from db: 
![image](https://github.com/bcgov/cas-cif/assets/77306764/0256ddc8-e101-4f6d-8428-b5f266282dfa)

2023-07-10 23:03 UTC, dleard approved these changes
:100: This was a big task. Nice work!
I've checked:
- The migration does not fail
- It creates the correct number of form_change records
- The form properly creates/updates EI report form_change records
- Table data is properly populated on commit
- Optional values are removed from the table data if removed on the form

This looks good to go, just needs a rebase

2023-07-11 15:36 UTC, merged