1703 4 hard delete attachments
bcgov/cas-cif pull request #1835
Opened 2023-08-04 15:02 UTC by BCerki

2023-08-04 22:27 UTC, BCerki commented
@dleard this is the attachments PR, and this is where Gurjeet fixed the middleware: https://github.com/bcgov/cas-cif/pull/1838

2023-08-08 21:02 UTC, Sepehr-Sobhani requested changes
Awesome! I just have a few leftover things and some curiosity questions :) Once the attachment upload feature is fixed, I would love to manually test this function.

2023-08-08 22:28 UTC, BCerki commented on .gitignore
> +gha-creds-*.json
This is leftover from experimenting with CI, will remove

2023-08-08 22:28 UTC, BCerki commented on schema/deploy/mutations/discard_project_attachment_form_change.sql
> +returns cif.form_change
If the return type is different you can't replace, you have to drop and remake

2023-08-08 22:31 UTC, Sepehr-Sobhani commented on schema/deploy/mutations/discard_project_attachment_form_change.sql
> +returns cif.form_change
Woooo, good to know 👍

2023-08-10 21:52 UTC, BCerki commented
work finished in #1843

2023-08-10 21:53 UTC, closed without merging