Chore: Relay 13
bcgov/cas-cif pull request #224
Opened 2022-01-14 23:15 UTC by pbastia

2022-01-15 00:01 UTC, pbastia commented on app/relay.config.json
> +  "schema": "./schema/schema.graphql"
the new relay compiler doesn't like it when the schema is in one of the excluded folders

2022-01-15 00:06 UTC, pbastia commented on app/relay.config.js
> +  schema: "./schema/schema.graphql",
the new `relay-compiler` doesn't like it when the schema is in one of the excluded folders

2022-01-15 00:06 UTC, pbastia commented on app/package.json
> +    "build:relay": "mkdir -p __generated__ && relay-compiler",
the new `relay-compiler` doesn't create the artifacts folder by default...but it's FAST

2022-01-17 16:16 UTC, matthieu-foucault approved these changes

2022-01-17 16:18 UTC, matthieu-foucault requested changes

2022-01-18 19:20 UTC, matthieu-foucault approved these changes

2022-01-18 19:20 UTC, merged