Chore: project managers computed column
bcgov/cas-cif pull request #290
Opened 2022-02-18 21:53 UTC by dleard

Adding multiple project managers will need to iterate over the # of records in the project_manager_label table and render a form whether there is form_data or not.

This computed column returns a composite return value that always contains one record for each project_manager_label and the form_data for that project and label if it exists.

Committed form_data is retrieved by latest updated (last committed).
Pending form_data takes precedence over committed form_data.
Pending form_data is only returned to the user who created it (allows concurrent editing).

2022-02-22 18:02 UTC, matthieu-foucault requested changes

2022-02-22 22:26 UTC, dleard commented on schema/deploy/computed_columns/project_revision_project_manager_form_changes_by_label.sql
> +  )
the filter on line 30 is unnecessary, I'll remove that one. But isn't filtering on `fc.created_by` on line 18 necessary if we decide to allow concurrent editing of the same revision?

2022-02-22 23:02 UTC, matthieu-foucault commented on schema/deploy/computed_columns/project_revision_project_manager_form_changes_by_label.sql
> +  )
Even if we decided to allow concurrent editing you'd want this function to return all the forms for the given revision, regardless of the user who created them. The constraints would be defined on how those forms can be edited, not what is returned here.

2022-02-23 00:36 UTC, dleard commented on schema/deploy/computed_columns/project_revision_project_manager_form_changes_by_label.sql
> +  )
Gotcha, I've updated the function not to filter by `created_by`. Instead it gets the latest pending change regardless of user

2022-02-23 00:43 UTC, matthieu-foucault approved these changes

2022-02-23 00:44 UTC, merged