Feat: edit operator
bcgov/cas-cif pull request #303
Opened 2022-02-28 22:21 UTC by pbastia

2022-03-03 00:05 UTC, dleard requested changes
looks good, just missing a verify

2022-03-03 00:07 UTC, matthieu-foucault submitted a review, later dismissed

2022-03-03 00:07 UTC, matthieu-foucault commented on app/lib/pages/relayFormPageFactory.tsx
> +    const [updateFormChange, isUpdatingFormChange] = useUpdateFormChange();
When fixing #285 we might need to make this hook a parameter of the factory

2022-03-08 17:20 UTC, matthieu-foucault commented on app/components/Operator/OperatorForm.tsx
> +      <Button type="submit">Submit</Button>
This button can use a margin on the right

2022-03-09 00:16 UTC, matthieu-foucault approved these changes
@dleard This needs your approval as well

2022-03-09 00:38 UTC, dleard approved these changes

2022-03-09 00:42 UTC, merged