Feat/project details
bcgov/cas-cif pull request #323
Opened 2022-03-07 20:30 UTC by BCerki

2022-03-07 20:40 UTC, BCerki commented on app/pages/cif/project/[project]/index.tsx
>    query ProjectOverwiewQuery($project: ID!) {
I was going to fix the typo in `ProjectOverwiewQuery` but then it occured to me changing a query name might cause problems elsewhere?

2022-03-07 20:41 UTC, BCerki commented on app/pages/cif/project/[project]/index.tsx
> +export const pageQuery = graphql`
I was going to change the variable name to `projectOverviewQuery`, but then it occurred to me that a name change might cause problems elsewhere?

2022-03-07 22:58 UTC, BCerki commented on app/pages/cif/project/[project]/index.tsx
> +            }
I still don't totally follow why I sometimes have to go through edges and nodes but sometimes I just go straight to the field I'm looking for

2022-03-07 22:59 UTC, BCerki commented on app/pages/cif/project/[project]/index.tsx
> +        <dd>{project.fundingStreamRfpByFundingStreamRfpId.year}</dd>
Have I got the correct data here? On the form it looked like the dropdown for Funding Stream RFP is just a list of years

2022-03-08 16:43 UTC, matthieu-foucault requested changes
Looking good! A couple of tweaks that can be done.

The spurious happo diffs are an issue, but not for this PR. We have a tech debt issue to solve those (#275 )

2022-03-10 15:29 UTC, matthieu-foucault approved these changes

2022-03-10 17:01 UTC, matthieu-foucault approved these changes

2022-03-10 17:02 UTC, merged