Feat/full name consistency
bcgov/cas-cif pull request #399
Opened 2022-03-22 21:33 UTC by gurjmatharu

2022-03-24 16:26 UTC, matthieu-foucault requested changes
You'll want to clean up your git history. Not sure what happened, but it looks like you merged two versions of your branch together after a rebase. A number of commits appear multiple times

2022-03-24 16:26 UTC, matthieu-foucault commented on app/components/Form/ProjectManagerForm.tsx
> +              familyName
Everywhere where both `givenName` and `familyName` are used, you want to use `fullName` instead

2022-03-29 19:26 UTC, matthieu-foucault requested changes

2022-03-29 19:26 UTC, matthieu-foucault commented on app/components/Form/ProjectManagerForm.tsx
> +          title: `${node.fullName}`,
```suggestion
          title: node.fullName,
```
no need for string interpolation here

2022-03-29 19:26 UTC, matthieu-foucault commented on app/components/Project/ProjectTableRow.tsx
> +                familyName
```suggestion
                fullName
```

2022-03-29 19:26 UTC, matthieu-foucault commented on app/components/User/UserProfile.tsx
> +          familyName
```suggestion
          fullName
```

2022-03-29 19:26 UTC, matthieu-foucault commented on app/pages/admin/users.tsx
> +            familyName
```suggestion
            fullName
```

2022-03-29 19:26 UTC, matthieu-foucault commented on app/pages/cif/project/[project]/index.tsx
> +        <dt>Project Manager 123</dt>
```suggestion
        <dt>Project Manager</dt>
```

2022-03-29 19:26 UTC, matthieu-foucault commented on app/tests/unit/components/Project/ProjectTableRow.test.tsx
> +                  familyName: "Manager last name 1",
use `fullName` here

2022-03-29 19:26 UTC, matthieu-foucault commented on schema/deploy/computed_columns/cif_user_full_name.sql
> +  select u.family_name || ', ' || u.given_name;
this will return `null` if either `family_name` or `given_name` is `null`. Check out `contact_full_name` to see how to handle `null` cases

2022-03-29 19:26 UTC, matthieu-foucault commented on schema/revert/computed_columns/full_name.sql
> +drop function cif.full_name(anyelement);
```suggestion
drop function cif.cif_user_full_name(cif.cif_user);
```

This file also needs to be renamed to match the change name

2022-03-30 17:19 UTC, gurjmatharu commented on schema/revert/computed_columns/full_name.sql
> +-- Revert cif:computed_columns/full_name from pg
renamed.

2022-03-30 17:20 UTC, matthieu-foucault approved these changes

2022-03-30 18:06 UTC, matthieu-foucault requested changes
Looks like there's a failing unit test

2022-03-30 19:49 UTC, gurjmatharu commented
> Looks like there's a failing unit test

Fixed.

2022-03-30 19:58 UTC, matthieu-foucault approved these changes

2022-03-30 19:58 UTC, merged