Feat/siteminder redirect
bcgov/cas-cif pull request #426
Opened 2022-03-29 15:27 UTC by mikevespi

Card: [305](https://app.zenhub.com/workspaces/climate-action-secretariat-60ca4121764d710011481ca2/issues/bcgov/cas-cif/305)

Note: `@bcgov-cas/sso-express` was bumped to version 3.1 to include changes that allow `authorizationUrlParams` which is used to skip the kc login page.

Add `SHOW_KC_LOGIN` env var. When false, the `log in` button takes users straight to the IDIR login page. 
![kc_login](https://user-images.githubusercontent.com/11034827/160648007-54712ddd-83ab-462e-948c-216020f5a7b6.gif)

2022-03-29 21:55 UTC, matthieu-foucault requested changes

2022-03-29 22:09 UTC, pbastia reviewed
You could add the `SHOW_KC_LOGIN` in the `app/.env.example` too

2022-03-29 22:09 UTC, matthieu-foucault submitted a review, later dismissed
just needs a `git rebase` and that's good to go

2022-03-29 22:22 UTC, matthieu-foucault submitted a review, later dismissed

2022-03-29 23:15 UTC, matthieu-foucault approved these changes

2022-03-30 16:09 UTC, matthieu-foucault approved these changes

2022-03-30 16:09 UTC, merged