feat: showing edit project state in task list
bcgov/cas-cif pull request #479
Opened 2022-04-07 19:15 UTC by gurjmatharu

2022-04-09 00:12 UTC, matthieu-foucault requested changes

2022-04-09 00:12 UTC, matthieu-foucault commented on app/tests/unit/pages/project-revision/[projectRevision]/index.test.tsx
> +
do you want to remove this?

2022-04-09 00:12 UTC, matthieu-foucault commented on app/cypress/integration/cif/project-revision/index.spec.js
>      cy.contains("Changes saved.");
```suggestion
    cy.contains("Changes saved.");
    cy.get("body").happoScreenshot({
      component: "Project Overview Form",
      variant: "editing",
    });
```

2022-04-09 02:59 UTC, gurjmatharu commented on app/tests/unit/pages/project-revision/[projectRevision]/index.test.tsx
> +
nope - this was a mistake, fixing.

2022-04-11 15:12 UTC, matthieu-foucault requested changes

2022-04-11 17:13 UTC, gurjmatharu commented on app/components/TaskList.tsx
>            </ul>
updated.

2022-04-11 18:15 UTC, matthieu-foucault approved these changes

2022-04-11 18:15 UTC, merged