chore: remove default image from postgres.yaml
bcgov/cas-cif pull request #581
Opened 2022-05-10 15:36 UTC by BCerki

Issue #527

2022-05-10 16:04 UTC, matthieu-foucault requested changes
All of the `image` tags are optional. We want to remove them to let the operator decide for us, and to have our images upgrade automatically when the operator is upgraded.

While we're at it, setting resources for the `pgMonitor`, and `replicaCertCopy` containers, as shown in https://github.com/bcgov/how-to-workshops/pull/12/, would reduce the resource usage of the cluster

2022-05-10 17:33 UTC, BCerki commented
> replicaCertCopy

I added limits for the `pgMonitor` but I didn't see a `replicaCertCopy` in the file

2022-05-10 17:37 UTC, matthieu-foucault commented
You'll have to add the entry for the `replicaCertCopy` configuration, as it's currently just using the default values.
See https://access.crunchydata.com/documentation/postgres-operator/v5/references/crd/#postgresclusterspecinstancesindexsidecarsreplicacertcopy

2022-05-11 15:38 UTC, matthieu-foucault approved these changes

2022-05-11 15:38 UTC, merged