Chore/627 GitHub registry
bcgov/cas-cif pull request #658
Opened 2022-05-25 19:12 UTC by gurjmatharu

2022-05-25 20:38 UTC, pbastia requested changes
we're missing the changes to artifactory url in the `values.yaml` file of the helm chart.
@matthieu-foucault do you know if it's something we need to setup, or if we can just use a predetermined proxy?

2022-05-26 16:34 UTC, matthieu-foucault commented
Looks like there is no remote repository setup for `ghcr.io`, so we'll have to stop using artifactory, which is okay since there are no cost/quotas.

See https://github.com/BCDevOps/developer-experience/blob/master/apps/artifactory/DEVHUB-README.md#how-do-i-find-out-what-repos-are-available to find out the available repos

2022-05-26 22:58 UTC, matthieu-foucault approved these changes
Looks good to me. A rebase might fix CI

2022-05-27 21:57 UTC, pbastia approved these changes

2022-05-27 21:58 UTC, pbastia requested changes
wait wait

2022-05-27 22:00 UTC, pbastia requested changes
something was copy pasted just a bit too quickly

2022-05-27 22:00 UTC, pbastia commented on chart/cas-cif/values.yaml
> +    repository: ghcr.io/bcgov/cas-cif-schema/cas-cif-app
This should be:

```suggestion
    repository: ghcr.io/bcgov/cas-cif-app
```

2022-05-27 22:17 UTC, pbastia approved these changes

2022-05-27 22:23 UTC, merged