Chore/contact button amendments
bcgov/cas-cif pull request #759
Opened 2022-06-20 20:02 UTC by Sepehr-Sobhani

2022-06-21 17:00 UTC, matthieu-foucault commented on app/components/Form/NewContactButton.tsx
> +  const clickHandler = (e: React.ChangeEvent<{}>) => {
Should the project_contact form_change be created now, or when the user submits the contact form?

2022-06-21 17:01 UTC, matthieu-foucault commented on app/components/Contact/ContactForm.tsx
>          Submit
the "discard" button below should redirect back to the project revision page

2022-06-24 19:52 UTC, matthieu-foucault commented
@Sepehr-Sobhani there's some conflicts that need to be resolved, can you rebase this?

2022-06-24 19:53 UTC, Sepehr-Sobhani commented
> @Sepehr-Sobhani there's some conflicts that need to be resolved, can you rebase this?

@matthieu-foucault On it

2022-06-27 16:06 UTC, matthieu-foucault requested changes
To add the button to the search dropdown widget, that widget could support a custom `uiSchema` option, e.g. `getAutocompleteProps: (WidgetProps) => AutocompletProps`, allowing you to customize the `Autocomplete` `ListboxComponent` prop.

2022-06-27 22:36 UTC, Sepehr-Sobhani commented on app/components/Form/NewContactButton.tsx
> +const NewContactButton: React.FC<Props> = ({
@matthieu-foucault Based on [this updated comment](https://github.com/bcgov/cas-cif/issues/695#issuecomment-1149232780), we needed to change its location.

2022-06-27 22:40 UTC, matthieu-foucault commented on app/components/Form/NewContactButton.tsx
> +const NewContactButton: React.FC<Props> = ({
In that case, I would argue that the button should use the `secondary` variant. We should only have one primary per page.

2022-06-28 16:15 UTC, matthieu-foucault submitted a review, later dismissed
There are some margin issues that we need to fix (too much space between a search dropdown and the button), but I think they need to be done at the field template level, so another PR would be better for that

2022-06-28 23:43 UTC, matthieu-foucault approved these changes

2022-06-28 23:44 UTC, merged