Refactor: reporting requirement db refactor Part 2
bcgov/cas-cif pull request #776
Opened 2022-06-23 21:51 UTC by dleard

issue #761
Part 2. The db changes here will have cascading effects on computed columns and front-end fragments and mutations.

2022-07-05 21:00 UTC, dleard commented on app/components/Form/Functions/projectMilestoneFormFunctions.tsx
> +  reportingRequirementEdges,
Add explicit types

2022-07-05 21:01 UTC, dleard commented on app/components/Form/Functions/projectMilestoneFormFunctions.tsx
> +  let consolidatedFormDataObject = {} as any;
Add explicit type

2022-07-06 19:56 UTC, matthieu-foucault requested changes

2022-07-06 19:56 UTC, matthieu-foucault commented on app/components/TaskList/index.tsx
> +              ({ node }) => node.formCompletionStatus === "Attention Required"
```suggestion
              ({ node }) => node.formCompletionStatus === ATTENTION_REQUIRED_STATUS
```

2022-07-06 19:56 UTC, matthieu-foucault commented on app/cypress/support/commands.js
> +    cy.get('[id*="certifierProfessionalDesignation"]').type(
we should use the testing-library commands whenever possible, i.e. `getByLabel`

2022-07-06 19:56 UTC, matthieu-foucault commented on app/data/jsonSchemaForm/paymentSchema.ts
> +      title: "Gross Amount",
```suggestion
      title: "Net Amount",
```

2022-07-06 19:56 UTC, matthieu-foucault commented on app/components/Form/reportingRequirementFormChangeFunctions.ts
> +        if (reportType)
Why do we need this condition here. The logic isn't obvious, it could use a comment

2022-07-06 19:56 UTC, matthieu-foucault commented on app/data/jsonSchemaForm/projectMilestoneSchema.ts
> +  maxiumAmount: {
```suggestion
  maximumAmount: {
```

2022-07-06 19:56 UTC, matthieu-foucault commented on schema/deploy/tables/budget_item.sql
>  );
This whole table should be deleted. We're not handling budget items in v1.0

2022-07-06 19:56 UTC, matthieu-foucault commented on schema/deploy/tables/reporting_requirement.sql
>  comment on column cif.reporting_requirement.description is 'A user defined description of a milestone';
```suggestion
comment on column cif.reporting_requirement.description is 'A user defined description of a reporting requirement';
```

2022-07-07 16:16 UTC, matthieu-foucault approved these changes

2022-07-07 16:31 UTC, merged