chore: unlink due date and received date widget
bcgov/cas-cif pull request #779
Opened 2022-06-24 01:28 UTC by Sepehr-Sobhani

Zenhub: [721](https://github.com/bcgov/cas-cif/issues/721)

2022-06-27 16:18 UTC, matthieu-foucault requested changes

2022-06-27 16:18 UTC, matthieu-foucault commented on app/tests/unit/lib/theme/widgets/ReceivedDateWidget.test.tsx
>    it("displays overdue text and icon if report is late", () => {
this whole test should be removed

2022-06-27 16:18 UTC, matthieu-foucault commented on app/lib/theme/widgets/ReceivedDateWidget.tsx
> +          </div>
Other than this, which could be a `contentPrefix` `uiSchema` property, this is a simple date widget now, right?

2022-06-27 16:18 UTC, matthieu-foucault commented on app/lib/theme/widgets/ReceivedDateWidget.tsx
> +          {value ? displayString : "Select a date"}
Do we even want to display "Select a date" ? If we do, should it be greyed out, at it's a placeholder?

2022-06-29 15:35 UTC, matthieu-foucault requested changes
just a little bit of cleanup needed in some test code

2022-06-29 15:35 UTC, matthieu-foucault commented on app/tests/unit/lib/theme/widgets/DateWidget.test.tsx
> +  // it("if report is upcoming, displays weeks until due", () => {
delete commented out code

2022-06-29 15:35 UTC, matthieu-foucault commented on app/tests/unit/lib/theme/widgets/DateWidget.test.tsx
> +    screen.logTestingPlaygroundURL();
```suggestion
```

2022-06-29 15:46 UTC, Sepehr-Sobhani commented on app/tests/unit/lib/theme/widgets/DateWidget.test.tsx
> +  // it("if report is upcoming, displays weeks until due", () => {
Oops 🤦‍♂️

2022-06-29 15:49 UTC, matthieu-foucault approved these changes

2022-06-29 16:23 UTC, merged