Chore: growthbook
bcgov/cas-cif pull request #840
Opened 2022-07-11 23:42 UTC by dleard

2022-07-18 17:45 UTC, mikevespi approved these changes
Looks great!

2022-07-18 20:20 UTC, mikevespi approved these changes
:shipit:

2022-07-18 22:27 UTC, pbastia requested changes
minor code style, awesome 👌

2022-07-18 22:27 UTC, pbastia commented on app/pages/_app.tsx
> +          });
this is not a response object anymore
```suggestion
          .then((jsonData) => {
            growthbook.setFeatures(jsonData.features);
          });
```

2022-07-18 22:27 UTC, pbastia commented on app/pages/_app.tsx
> +  useMemo(() => {
I would add a small comment about the caveat that the use of `useMemo` here means the feature toggle in growthbook means the change won't be visible for a user until they refresh the page

2022-07-18 22:27 UTC, pbastia commented on docs/developer-guide.md
> +const showFlaggedFeature = useFeature('flagged-item').on; // Set the value of useFeature.on to a boolean variable
```suggestion
const showFlaggedFeature = useFeature('flagged-feature').on; // Set the value of useFeature.on to a boolean variable
```

2022-07-19 16:41 UTC, pbastia approved these changes

2022-07-19 16:41 UTC, merged