fix: use mocked time to solve happo diffs
bcgov/cas-cif pull request #936
Opened 2022-08-05 20:07 UTC by Sepehr-Sobhani

ZH: https://github.com/bcgov/cas-cif/issues/929

2022-08-05 20:32 UTC, BCerki approved these changes

2022-08-05 20:39 UTC, Sepehr-Sobhani commented
@BCerki after looking at happo diffs, I found an issue with the mocked time I've implemented; I've added mocked time as today but `Complete` badge is showing yesterday. I think I need to change the mocked time to a full timestamptz.

2022-08-08 16:17 UTC, pbastia requested changes
super nitpicky comment ;) Looks great, thank you!

2022-08-08 16:17 UTC, pbastia commented on app/cypress/support/commands.js
> +    let mockedTimeCookie = cookies.filter(
this can be a const too

2022-08-08 16:56 UTC, Sepehr-Sobhani commented on app/cypress/support/commands.js
> +    let mockedTimeCookie = cookies.filter(
Done

2022-08-08 16:58 UTC, pbastia submitted a review, later dismissed

2022-08-08 18:44 UTC, pbastia approved these changes
💯

2022-08-08 18:44 UTC, merged