Feat/additional overview fields
bcgov/cas-cif pull request #938
Opened 2022-08-08 14:48 UTC by BCerki

Card: https://app.zenhub.com/workspaces/climate-action-secretariat-60ca4121764d710011481ca2/issues/bcgov/cas-cif/858

2022-08-08 18:39 UTC, BCerki commented on schema/deploy/tables/project_type.sql
> +-- Grant cif_guest no permissions
Is this necessary? I grabbed it from another table

2022-08-10 19:08 UTC, dleard requested changes

2022-08-10 19:08 UTC, dleard commented on app/components/Form/SelectProjectTypeWidget.tsx
> +  console.log("formContext.form", formContext.form);
```suggestion
```

2022-08-10 20:26 UTC, BCerki commented on app/lib/theme/widgets/DecimalWidget.tsx
> +export const DecimalWidget: React.FC<WidgetProps> = ({
https://github.com/bcgov/cas-cif/issues/959

2022-08-15 20:54 UTC, dleard approved these changes

2022-08-15 20:54 UTC, merged