Feat/teimp duration
bcgov/cas-cif pull request #962
Opened 2022-08-10 23:59 UTC by mikevespi

Card: https://app.zenhub.com/workspaces/climate-action-secretariat-60ca4121764d710011481ca2/issues/bcgov/cas-cif/763

2022-08-12 20:29 UTC, matthieu-foucault requested changes
just a couple of extra test cases and some comments needed, looks good otherwise

2022-08-12 20:29 UTC, matthieu-foucault commented on app/lib/helpers/getDurationFromDates.ts
> +const getDurationFromDates = (startDate: string, endDate: string) => {
Can we have a small comment indicating the format this function returns the duration in?

2022-08-12 20:29 UTC, matthieu-foucault commented on app/lib/theme/widgets/DateWidget.tsx
> +          gap: 1rem;
I didn't know about the `gap` property, that's handy!

2022-08-12 20:29 UTC, matthieu-foucault commented on app/tests/unit/components/Form/ProjectEmissionIntensityReportForm.test.tsx
> +    expect(screen.getByText(/duration: 12 months/i)).toBeInTheDocument();
duplicate line

2022-08-12 20:29 UTC, matthieu-foucault commented on app/tests/unit/lib/helpers/getDurationFromDates.test.ts
> +describe("The getDurationFromDates helper method", () => {
can we test the cases where the number or months or days are `0`

2022-08-15 20:19 UTC, BCerki approved these changes

2022-08-19 20:19 UTC, matthieu-foucault approved these changes

2022-08-19 21:00 UTC, dleard approved these changes

2022-08-19 21:00 UTC, merged