Feat: TEIMP payment information with calculated values
bcgov/cas-cif pull request #963
Opened 2022-08-11 00:12 UTC by pbastia

2022-08-12 17:05 UTC, matthieu-foucault reviewed
will finish reviewing later

2022-08-12 17:05 UTC, matthieu-foucault commented on schema/test/unit/computed_columns/emission_intensity_report_calculated_ei_performance_test.sql
> +  values (1, 1, 1, 2, 3), (2, 1, null, 2, 3), (3, 1, 1, null, 3), (4, 1, 1, 2, null);
Do you need to add tests reflecting the changes you made to `cif.emission_intensity_report_calculated_ei_performance`, i.e., handle null `post_project_emission_intensity` and `baseline_emission_intensity = target_emission_intensity`

2022-08-12 20:16 UTC, matthieu-foucault approved these changes
Other than the two minor comments above, and a rebase needed, this looks good to me

2022-08-19 18:32 UTC, matthieu-foucault approved these changes

2022-08-19 18:35 UTC, matthieu-foucault requested changes
Some rendering issue visible on Happo

![image](https://user-images.githubusercontent.com/2684022/185684926-9852fc0f-c3cd-41b2-9232-af6f4b88dd38.png)

2022-08-19 18:40 UTC, pbastia commented
Spotted a glitch in the summary, but let's approve this since this is going to get refactored
![image](https://user-images.githubusercontent.com/11507754/185685539-30839fe2-830c-4b0a-9bac-9d9a0ce5bb9a.png)

2022-08-19 18:41 UTC, matthieu-foucault approved these changes

2022-08-19 18:41 UTC, merged